-- MySQL Script generated by MySQL Workbench
-- Fri May 10 11:09:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema inTouch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inTouch` DEFAULT CHARACTER SET utf8 ;
USE `inTouch` ;

-- -----------------------------------------------------
-- Table `inTouch`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nick_UNIQUE` (`username` ASC),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC))
  ;


-- -----------------------------------------------------
-- Table `inTouch`.`Friendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`Friendship` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `friend1` INT(11) NOT NULL,
  `friend2` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Friendship_User1_idx` (`friend1` ASC),
  INDEX `fk_Friendship_User2_idx` (`friend2` ASC),
  CONSTRAINT `fk_Friendship_User1`
    FOREIGN KEY (`friend1`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friendship_User2`
    FOREIGN KEY (`friend2`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `inTouch`.`SocialGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`SocialGroup` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creationDate` DATE NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `inTouch`.`Membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`Membership` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin` TINYINT(1) NOT NULL DEFAULT '0',
  `socialGroup` INT(11) NOT NULL,
  `member` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Membership_Group1_idx` (`socialGroup` ASC),
  INDEX `fk_Membership_User1_idx` (`member` ASC),
  CONSTRAINT `fk_Membership_Group1`
    FOREIGN KEY (`socialGroup`)
    REFERENCES `inTouch`.`SocialGroup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membership_User1`
    FOREIGN KEY (`member`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `inTouch`.`PendingFriendship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`PendingFriendship` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sender` INT(11) NOT NULL,
  `receiver` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Friendship_User_idx` (`sender` ASC),
  INDEX `fk_Friendship_User1_idx` (`receiver` ASC),
  CONSTRAINT `fk_Friendship_User`
    FOREIGN KEY (`sender`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friendship_User3`
    FOREIGN KEY (`receiver`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `inTouch`.`PendingMembership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`PendingMembership` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `invitation` TINYINT(1) NOT NULL,
  `user` INT(11) NOT NULL,
  `socialGroup` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PendingMembership_User1_idx` (`user` ASC),
  INDEX `fk_PendingMembership_Group1_idx` (`socialGroup` ASC),
  CONSTRAINT `fk_PendingMembership_Group1`
    FOREIGN KEY (`socialGroup`)
    REFERENCES `inTouch`.`SocialGroup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PendingMembership_User1`
    FOREIGN KEY (`user`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `inTouch`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inTouch`.`Post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(500) NULL DEFAULT NULL,
  `publishedDate` DATE NOT NULL,
  `socialGroup` INT(11) NULL DEFAULT NULL,
  `author` INT(11) NOT NULL,
  `private` TINYINT(1) NOT NULL DEFAULT '1',
  `attachment` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_Group1_idx` (`socialGroup` ASC),
  INDEX `fk_Post_User1_idx` (`author` ASC),
  CONSTRAINT `fk_Post_Group1`
    FOREIGN KEY (`socialGroup`)
    REFERENCES `inTouch`.`SocialGroup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`author`)
    REFERENCES `inTouch`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;
